spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

application:
  reader:
    max-allowed-book: 4

#чтение List - tags[1, 2, 3]
#application:
#  reader:
#    tags:
#      - 1
#      - 2
#      - 3

#чтение Map
#application:
#  reader:
#    tags:
#      - first: 1
#      - second: 2
#      - third: 3
